### ISSUE TITLE
bug: Fullscreen blocks pointer events from passing through

### ISSUE THREAD

**Issue by wrangelvid** [pmndrs/uikit#107]
Upgrading to uikit@4.0.0 alongside pmndrs/pointer-events@6.1.0 causes the Fullscreen component to block pointer events from passing through. This issue occurs only when using the experimental pointer events. For reproduction, see this [Stackblitz example](https://stackblitz.com/edit/vitejs-vite-ffjwgz?file=src%2FApp.tsx).

**Comment by bbohlender** [comment]
@wrangelvid This is actually by design, but I forgot to mention it in the release notes. Will fix that

This aligns uikit closer to CSS, where the default pointer-events is equal to "auto" and not "listener," which is assumed by default by pmndrs/pointer-events.

Setting pointerEvents="listener" on the root / fullscreen will revert back to the previous behavior :)
