### ISSUE TITLE
Native?

### ISSUE THREAD

**Issue by jmatsushita** [pmndrs/uikit#16]
Hi there,

in his [tweet](https://x.com/0xca0a/status/1763174446200676661?s=46&t=Z5dH4We-lt6mErLL_spz3A) @drcmda mentioned that uikit will run in native. Would you mind expanding on this? How would it work and on which platforms?

Cheers,

Jun

**Comment by bbohlender** [comment]
Hey @jmatsushita 

native was referring to react-native using expo-gl. Therefore as far as I know, only Android and iOS are supported.
Three.js works on Android and iOS and since thats what uikit uses, it doesnt work any different on those platforms.
(expo-gl transforms the WebGL calls to native opengles calls as far as I know)

**Comment by bbohlender** [comment]
I've started a branch with react-native & expo, if you are interested
check out branch feature/expo

**Comment by jmatsushita** [comment]
Thanks so much @bbohlender ! Awesome work. I'll give the branch a try right now and let you know how it went.

**Comment by bbohlender** [comment]
@jmatsushita here's a better explanation of the state of the branch (as I said in there, help is always appreciated)
https://github.com/pmndrs/uikit/issues/17#issuecomment-1992701847

**Comment by bbohlender** [comment]
As I said in the linked comment
pnpm  and expo don't really like each other and after a few hours I gave up on using only pnpm
I would be happy if someone figures a better option, but this workarround is only necassary in monorepos where the build libraries are linked with symlinks, which metro was not happy about when resolving images inside  node_modules folders from symlinked libraries.

The wonkiness is due to the buffers not beeing correctly updated by expo-gl, so that needs a fix inside expo :(
