### ISSUE TITLE
[Vanilla] - `hover` and `active` props do not seem to work after `0.3.4`

### ISSUE THREAD

**Issue by michealparks** [pmndrs/uikit#72]
Hello, first I just want to say thank you for this incredible library!

I'm a Threlte maintainer and over the past few weeks I've been working on a Threlte library that wraps the vanilla UIKit export (`@pmndrs/uikit`). After upgrading from `0.3.4`, `hover` and `active` props seem to no longer have any effect. I've created two small stackblitz repos to demonstrate:

* [0.3.4 - Working](https://stackblitz.com/edit/vitejs-vite-84zvva?file=src%2FScene.svelte)
* [0.3.5 - Not working](https://stackblitz.com/edit/vitejs-vite-cyqzbx?file=src%2FScene.svelte)

**Comment by mrxz** [comment]
Ran into the same issue when updating from v0.3.4 to v0.3.6 in my project. Turns out that for vanilla projects the eventnames are now expected to be lowercase (https://github.com/pmndrs/uikit/commit/9d52cc8ec96fac2167d997373c740c196e38bbbd), so `pointerover` instead of `pointerOver`. I've created a PR (#73) to update the docs and example to reflect this, but obviously we'll have to change the eventnames on our ends as well.

**Comment by bbohlender** [comment]
@michealparks @mrxz 
Sorry, I actually wasn't aware of anybody already using those events. In the future, I'll make sure I create a release note at least; sorry for the inconvenience.

It was actually planned to do a threlte version of that, so I am very excited that somebody is already doing that.

I'd like to learn more about your use case and technology stack since I am also working on unpublished complementary libraries that might be interesting. Consider DMing me on twitter / discord in case any of you wants to chat!
