### ISSUE TITLE
Pass pointer events into on[Hover/Active/Focus]Change

### ISSUE THREAD

**Issue by wrangelvid** [pmndrs/uikit#86]
I really started liking onHoverChange, onActiveChange etc. but wish the pointer event would be passed into that. For example, holding the shift key may enable toggling many selection containers when hovering over it, which can be implemented by retrieving the key press from the pointer.

**Comment by bbohlender** [comment]
I think normal `onPointerOver` events are a better fit for this use case. `on[X]Change` are currently really just listeners for the respective signals used under the hood to have the respective conditional properties

**Comment by wrangelvid** [comment]
I should've been more precise in requesting this only for `onHoverChange`, `onActiveChange` and `onFocusChange` and not all conditionals. The [Interactivity](docs/tutorials/interactivity.md) tutorial states that all UI elements can receive events like other r3f elements but extends it with `hover` and `active`. That implication makes it natural to include the pointer events into these. Then the [Event Properties](https://github.com/pmndrs/uikit/blob/296c891b0351a5420a7f786b0c248cad330a8b64/docs/getting-started/components-and-properties.md?plain=1#L504) could document `on[Hover/Active/Focus]Change` while `hover`, `active`, and `focus` remain in the conditionals.

**Comment by bbohlender** [comment]
onHoverChange etc should imo not receive an event because that leads people to believe onHoverChange is a combination of onPointerOver & onPointerOut. However, the hover state is much more complex as it tracks the amount of pointer that are currently hovering and only changes the hover state if the amount is or is not greater than 0.

Your example use case is not fitting here, because in a case where the user is hovering with 1 pointer where no additional button is pressed and then also hovering with another pointer (e.g. controller) with a specific button pressed onHoverChange is only executed initially and only the initial event would be provided. Therefore the developer would not be notified of the second pointer and its event. This illustrates my point where I fear that people can confuse onHoverChange etc with the actual pointer event which is what should be used for your presented use case.

If you find a use case where having the initial and last event for the hover etc. change is necassary, please let me know :)

**Comment by wrangelvid** [comment]
That makes sense, thank you for the clarification.
